apiVersion: v1
kind: Service
metadata:
  name: {{ include "lightrag.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "lightrag.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.config.server.port }}
    protocol: TCP
    name: http
  selector:
    {{- include "lightrag.selectorLabels" . | nindent 4 }}
