apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: lightrag-prod

resources:
  - namespace.yaml
  - secret.yaml
  - configmap.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - route.yaml

commonLabels:
  app: lightrag
  environment: production
  managed-by: kustomize
